version: '3.5'
services:
  db:
    build: psql/.
    image: terra-psql
    command: postgres -c 'max_connections=10'
    environment:
      - POSTGRES_DB=terra
      - POSTGRES_USER=terra_admin
      - POSTGRES_PASSWORD=krpec
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d f3 -U terra_admin"]
      interval: 5s
      start_period: 5s
networks:
  default:
    name: terra_network
